### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by dxfan227** [kyle-kelly/MMM-lyft#3]
Getting this in my logs every so often

`TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/home/pi/MagicMirror/modules/MMM-lyft/node_helper.js:79:95)
    at self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/pi/MagicMirror/node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)`

**Comment by kyle-kelly** [comment]
Looks like you're making faulty calls periodically, which isn't unusual. However no status code is being reported with the error. Unfortunately, I've lost full access to the docs because Lyft seems to have changed their developer program. I reapplied and will look into this when I can...

**Comment by dxfan227** [comment]
No problem, thanks for the great module! It’s awesome
